name: smartwind
description: NorthSails Smart Wind


publish_to: 'none'

version: 1.1.98+138

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #  firebase------------------------------------------
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  firebase_auth: ^3.8.0
  firebase_messaging: ^13.0.1
  firebase_database: ^9.1.4
  firebase_auth_platform_interface: ^6.7.0
  firebase_core_web: ^1.7.2

  #  --------------------------------------------------

  flutter_share: 2.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_pdfview: ^1.2.3
  flutter_inappwebview: ^5.4.3+7
  flutter_dropzone: ^3.0.5

  #  --------------------------------------------------
  dio: ^4.0.6
  percent_indicator: ^4.2.2
  nfc_manager: ^3.1.1
  shared_preferences: ^2.0.15
  animations: ^2.0.4
  image_picker: ^0.8.5+3
  jwt_decode: ^0.3.1
  webview_flutter: ^3.0.4
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  hex: ^0.2.0
  package_info_plus: ^1.4.3+1
  dropdown_search: ^5.0.2
  measured_size: ^1.0.0
  device_information: ^0.0.4
  device_info: ^2.0.3
  cached_network_image: ^3.2.2
  video_player: ^2.4.7
  group_list_view: ^1.1.1
  data_table_2: ^2.3.7


  custom_webview:
    path: ./Pugins/custom_webview
  json_annotation: ^4.6.0

  graphql_flutter: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

  splash_screen_view: ^3.0.0
  decorated_icon: ^1.2.1
  #  ota_update: ^4.0.1
  timeline_tile: ^2.0.0

  dotted_border: ^2.0.0+2
  socket_io_client: ^2.0.0
  file_picker: ^5.0.1
  universal_html: ^2.0.8
  dropdown_button2: ^1.8.0
  pdfx: ^2.2.0
  textfield_search: ^0.10.0
  searchfield: ^0.7.0
  csv: ^5.0.1
  pdf_render: ^1.3.2
  syncfusion_flutter_charts: ^20.2.48
  random_password_generator: ^0.2.1
  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  app_settings: ^4.1.8
  contextmenu: ^3.0.0
  syncfusion_flutter_datepicker: ^20.2.48
  badges: ^2.0.3
  just_the_tooltip: ^0.0.12



dev_dependencies:

  hive_generator: ^1.1.3
  json_serializable:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_web_compilers: ^3.2.5
  flutter_lints: ^2.0.1

flutter:

  assets:
    - assets/accountBlocked.jpg
    - assets/fileNotFound.png
    - assets/fonts/NsIcons.ttf
    - assets/images/background.jpg
    - assets/images/dark_background.jpg
    - assets/images/user.png
    - assets/images/userPlaceholder.jpg
    - assets/js.js
    - assets/js1.txt
    - assets/loginVideo.mp4
    - assets/noResult.png
    - assets/noResult111.jpg
    - assets/north_sails_logo.png
    - assets/north_sails_logo_tr.png
    - assets/north_sails_logox50.png
    - assets/QACheckList.json
    - assets/splash.png
    - assets/splash1.png
    - assets/uc.png
    - assets/uc1.png
    - assets/x.pdf
  uses-material-design: true
  fonts:
    - family: NsIcons
      fonts:
        - asset: assets/fonts/NsIcons.ttf








splash_screen_view:

  color: "#ffffff"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  image: assets/splash.png

  #color_dark: "#042a49"
  background_image_dark: "assets/images/dark_background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  android_gravity: center
  #ios_content_mode: center
  web_image_mode: center

  fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
