name: smartwind_future_fibers
description: NorthSails Smart Wind project for Future Fibers


publish_to: 'none'

version: 1.4.2+252

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  custom_webview:
    path: ./Pugins/custom_webview
  #  smartwind_login:
  #    path: ../../smartwind_flutter_packages/smartwind_login


  #  firebase------------------------------------------
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_auth: ^4.4.0
  firebase_messaging: ^14.4.0
  firebase_database: ^10.1.0
  #  firebase_auth_platform_interface: ^6.13.0
  #  firebase_core_web: ^2.3.0
  #  --------------------------------------------------


  flutter_share: 2.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_pdfview: ^1.3.0
  flutter_inappwebview: ^5.7.2+3
  flutter_dropzone: ^3.0.5

  #  --------------------------------------------------
  dio: ^5.1.1
  percent_indicator: ^4.2.3
  nfc_manager: ^3.2.0
  shared_preferences: ^2.1.0
  animations: ^2.0.7
  #  jwt_decode: ^0.3.1
  webview_flutter: ^4.0.7
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  hex: ^0.2.0
  package_info_plus: ^3.1.0
  #  dropdown_search: ^5.0.6
  measured_size: ^1.0.0
  device_information: ^0.0.4
  device_info: ^2.0.3
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  group_list_view: ^1.1.1
  data_table_2: ^2.4.2



  json_annotation: ^4.8.0


  hive: ^2.2.3
  #  hive_flutter: ^1.1.0
  uuid: ^3.0.7

  splash_screen_view: ^3.0.0
  decorated_icon: ^1.2.1
  #  ota_update: ^4.0.1
  timeline_tile: ^2.0.0

  dotted_border: ^2.0.0+3
  #  socket_io_client: ^2.0.1
  file_picker: ^5.2.7
  universal_html: ^2.2.1
  #  dropdown_button2: ^2.0.0
  pdfx: ^2.3.0
  #  textfield_search: ^0.10.0
  searchfield: ^0.7.6
  csv: ^5.0.1
  pdf_render: ^1.3.8

  syncfusion_flutter_pdf: ^21.1.38
  syncfusion_flutter_charts: ^21.1.38
  syncfusion_flutter_datepicker: ^21.1.38
  syncfusion_flutter_sliders: ^21.1.38
  #  syncfusion_flutter_pdfviewer: ^20.4.50
  #  syncfusion_pdfviewer_platform_interface: ^20.4.50



  random_password_generator: ^0.2.1
  #  flutter_slidable: ^2.0.0
  intl: ^0.17.0
  app_settings: ^4.2.0
  contextmenu: ^3.0.0
  #  badges: ^3.0.3
  just_the_tooltip: ^0.0.12
  #  url_launcher: ^6.1.10

  #  json_theme: ^4.0.3+2
  restart_app: ^1.1.2
  #  pdf_thumbnail: ^0.1.5+1

  dart_ping: ^8.0.1




dev_dependencies:
  dependency_validator: ^3.2.2
  hive_generator: ^2.0.0
  json_serializable:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_web_compilers: ^3.2.7
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.0

flutter:

  assets:
    - assets/accountBlocked.jpg
    - assets/android/loginVideo.mp4
    - assets/appainter_theme.json
    - assets/fileNotFound.png
    - assets/find.jpg
    - assets/fonts/NsIcons.ttf
    - assets/ic_launcher-playstore.png
    - assets/images/background.jpg
    - assets/images/background1.jpg
    - assets/images/dark_background.jpg
    - assets/images/dark_background1.jpg
    - assets/images/user128.png
    - assets/images/user164.png
    - assets/images/user256.png
    - assets/images/user512.png
    - assets/images/user64.png
    - assets/Newfolder.zip
    - assets/noPermissions.png
    - assets/noResult.png
    - assets/noResult111.jpg
    - assets/QACheckList.json
    - assets/rf/rf.js
    - assets/sample.pdf
    - assets/smartwindlogo.jpg
    - assets/smartwindLogo.png
    - assets/smartwindlogo100.jpg
    - assets/smartwindlogo150.jpg
    - assets/splash.png
    - assets/splash1.png
    - assets/uc.png
  uses-material-design: true
  fonts:
    - family: NsIcons
      fonts:
        - asset: assets/fonts/NsIcons.ttf



