name: smartwind
description: NorthSails Smart Wind


publish_to: 'none'


version: 1.1.21+62

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #  firebase------------------------------------------
  firebase_core: ^1.16.0
  firebase_analytics:
  firebase_crashlytics: ^2.7.2
  firebase_auth: ^3.3.17
  firebase_messaging: ^11.3.0

  #  --------------------------------------------------
  dio: ^4.0.6
  percent_indicator: ^4.0.1
  nfc_manager: ^3.1.1
  shared_preferences: ^2.0.13
  animations: ^2.0.2
  image_picker: ^0.8.5

  jwt_decode: ^0.3.1
  flutter_share: ^2.0.0

  flutter_barcode_scanner: ^2.0.0

  webview_flutter: ^3.0.2
  permission_handler: ^9.2.0
  path_provider: ^2.0.9
  flutter_pdfview: ^1.2.2
  hex: ^0.2.0
  package_info_plus: ^1.4.2

  dropdown_search: ^3.0.1
  measured_size: ^1.0.0

  device_information: ^0.0.4
  device_info: ^2.0.3
  firebase_database: ^9.0.13
  cached_network_image: ^3.2.0
  video_player: ^2.4.0
  group_list_view: ^1.1.1
  data_table_2: ^2.2.1


  custom_webview:
    path: ./Pugins/custom_webview
  json_annotation: ^4.5.0
  flutter_inappwebview: ^5.4.3+7
  graphql_flutter: ^5.1.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

  splash_screen_view: ^3.0.0
  decorated_icon: ^1.2.1
  ota_update: ^4.0.1
  timeline_tile: ^2.0.0
  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0+2
  socket_io_client: ^1.0.2
  file_picker: ^4.5.1
  universal_html: ^2.0.8
  dropdown_button2: ^1.4.0
  pdfx: ^2.0.1+2
  textfield_search: ^0.10.0
  searchfield: ^0.6.4
  csv: ^5.0.1
  pdf_render: ^1.0.23


dev_dependencies:

  hive_generator: ^1.1.2
  json_serializable:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_web_compilers: ^3.2.3
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
  fonts:
    - family: NsIcons
      fonts:
        - asset: assets/fonts/NsIcons.ttf


  assets:
    - assets/





splash_screen_view:

  color: "#ffffff"
  #background_image: "assets/splashscreen_image.png"

  # Optional parameters are listed below.
  image: assets/splash.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
