name: smartwind_future_fibers
description: NorthSails Smart Wind project for Future Fibers


publish_to: 'none'

version: 1.6.2+262

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  custom_webview:
    path: ./Pugins/custom_webview

  deebugee_plugin:
    path: ../../../../DeeBugee/deebugee_plugin


  #  firebase------------------------------------------
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.3
  firebase_database: ^10.2.3


  flutter_share: 2.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_pdfview: ^1.3.1
  flutter_inappwebview: ^5.7.2+3
  flutter_dropzone: ^3.0.5

  #  --------------------------------------------------
  dio: ^5.2.1+1
  percent_indicator: ^4.2.3
  nfc_manager: ^3.3.0
  shared_preferences: ^2.1.2
  animations: ^2.0.7
  webview_flutter: ^4.2.2
  permission_handler: ^10.3.0
  path_provider: ^2.0.15
  hex: ^0.2.0
  package_info_plus: ^3.1.0
  measured_size: ^1.0.0
  device_information: ^0.0.4
  #  device_info: ^2.0.3
  device_info_plus: ^4.0.0
  cached_network_image: ^3.2.3
  video_player: ^2.6.1
  group_list_view: ^1.1.1
  data_table_2: ^2.5.3



  json_annotation: ^4.8.1


  hive: ^2.2.3
  uuid: ^3.0.7

  splash_screen_view: ^3.0.0
  decorated_icon: ^1.2.1
  timeline_tile: ^2.0.0

  dotted_border: ^2.0.0+3
  file_picker: ^5.2.7
  universal_html: ^2.2.3
  csslib: 0.17.3
  pdfx: ^2.3.0
  searchfield: ^0.8.3
  csv: ^5.0.2
  pdf_render: ^1.3.8

  syncfusion_flutter_pdf: ^21.2.10
  syncfusion_flutter_charts: ^21.2.10
  syncfusion_flutter_datepicker: ^21.2.10
  syncfusion_flutter_sliders: ^21.2.10



  random_password_generator: ^0.2.1
  intl: ^0.18.1
  app_settings: ^4.2.0
  contextmenu: ^3.0.0
  just_the_tooltip: ^0.0.12
  restart_app: ^1.2.1

  dart_ping: ^8.0.1




dev_dependencies:
  dependency_validator: ^3.2.2
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_web_compilers: ^4.0.3
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.5

flutter:

  assets:
    - assets/accountBlocked.jpg
    - assets/android/loginVideo.mp4
    - assets/appainter_theme.json
    - assets/fileNotFound.png
    - assets/find.jpg
    - assets/fonts/NsIcons.ttf
    - assets/ic_launcher-playstore.png
    - assets/images/background.jpg
    - assets/images/background1.jpg
    - assets/images/dark_background.jpg
    - assets/images/dark_background1.jpg
    - assets/images/user128.png
    - assets/images/user164.png
    - assets/images/user256.png
    - assets/images/user512.png
    - assets/images/user64.png
    - assets/Newfolder.zip
    - assets/noPermissions.png
    - assets/noResult.png
    - assets/noResult111.jpg
    - assets/QACheckList.json
    - assets/rf/rf.js
    - assets/sample.pdf
    - assets/smartwindlogo.png
    - assets/smartwindlogo100.png
    - assets/smartwindlogo150.png
    - assets/smartwindlogo50.png
    - assets/smartwindlogos.zip
    - assets/uc.png
  uses-material-design: true
  fonts:
    - family: NsIcons
      fonts:
        - asset: assets/fonts/NsIcons.ttf



