name: smartwind
description: NorthSails Smart Wind


publish_to: 'none'


version: 1.1.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0

  #  firebase------------------------------------------
  firebase_core: ^1.4.0
  firebase_analytics:
  firebase_crashlytics: ^2.1.1
  firebase_auth: ^3.0.1
  firebase_messaging: ^10.0.4
  google_ml_vision: ^0.0.6
  #  --------------------------------------------------
  http: ^0.13.3
  dio: ^4.0.0
  percent_indicator: ^3.0.1
  nfc_manager: ^3.1.0
  shared_preferences: ^2.0.6
  animations: ^2.0.1
  image_picker: ^0.8.3
  jwt_decode: ^0.3.1
  flutter_share: ^2.0.0

  webview_flutter: ^2.0.10
  permission_handler: ^8.1.4+2
  flutter_barcode_scanner: ^2.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_pdfview: ^1.1.0
  hex: ^0.2.0


dev_dependencies:
  json_serializable:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/

