/// Flutter icons NsIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NsIcons
///      fonts:
///       - asset: fonts/NsIcons.ttf
///
/// 
///
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class NsIconsSuper {


  static const IconData rush = Icons.offline_bolt_outlined;
  static const IconData print = Icons.print_outlined;
  static const IconData printDisable = Icons.print_disabled_outlined;
  static const IconData crossProduction = Icons.merge_type_outlined;
}
