// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgW6bXgp0PmoKNcAUsAzTqOS8YYFPd0dM',
    appId: '1:27155477934:web:1ff8578ac037a6e330043f',
    messagingSenderId: '27155477934',
    projectId: 'smart-wind',
    authDomain: 'smart-wind.firebaseapp.com',
    databaseURL: 'https://smart-wind-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wind.appspot.com',
    measurementId: 'G-SEBNEV8XVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBggKndNStZQHrA00JqSbtlkUs6Cz9s3OI',
    appId: '1:27155477934:android:4c5c6688d51ead0730043f',
    messagingSenderId: '27155477934',
    projectId: 'smart-wind',
    databaseURL: 'https://smart-wind-default-rtdb.firebaseio.com',
    storageBucket: 'smart-wind.appspot.com',
  );
}
