/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String accountBlocked = "assets/accountBlocked.jpg";
  static const String appainter_theme = "assets/appainter_theme.json";
  static const String background = "assets/images/background.jpg";
  static const String dark_background = "assets/images/dark_background.jpg";
  static const String fileNotFound = "assets/fileNotFound.png";
  static const String find = "assets/find.jpg";
  static const String loginVideo = "assets/android/loginVideo.mp4";
  static const String noPermissions = "assets/noPermissions.png";
  static const String noResult = "assets/noResult.png";
  static const String noResult111 = "assets/noResult111.jpg";
  static const String north_sails_logo = "assets/north_sails_logo.png";
  static const String north_sails_logo_tr = "assets/north_sails_logo_tr.png";
  static const String north_sails_logox50 = "assets/north_sails_logox50.png";
  static const String NsIcons = "assets/fonts/NsIcons.ttf";
  static const String QACheckList = "assets/QACheckList.json";
  static const String rf = "assets/rf/rf.js";
  static const String sample = "assets/sample.pdf";
  static const String splash = "assets/splash.png";
  static const String splash1 = "assets/splash1.png";
  static const String uc = "assets/uc.png";
  static const String user128 = "assets/images/user128.png";
  static const String user164 = "assets/images/user164.png";
  static const String user256 = "assets/images/user256.png";
  static const String user512 = "assets/images/user512.png";
  static const String user64 = "assets/images/user64.png";
}
